apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: banking-system
  labels:
    app: notification-service
type: Opaque
stringData:
  MONGODB_PASSWORD: "notif_pass"
  RABBITMQ_PASSWORD: "guest"
