apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: banking-system
  labels:
    app: notification-service
spec:
  type: NodePort
  selector:
    app: notification-service
  ports:
    - name: http
      port: 8004
      targetPort: http
